services:
  frontend:
    build: ./frontend
    container_name: 5g-sport-frontend
    env_file: ./frontend/.env
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
      - CI=true
    stdin_open: true
    tty: true
  server:
    build: ./server
    container_name: 5g-sport-server
    ports:
        - "5000:5000"
    depends_on:
      - mediamtx
    devices:
      - /dev/video0:/dev/video0
    privileged: true
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: 5g-sport-mediamtx
    ports:
      - "8554:8554"
      - "8889:8889"