services:
  frontend:
    build: ./frontend
    container_name: 5g-sport-frontend
    ports:
      - "3000:3000"
    env_file: ./frontend/.env
    environment:
      - WATCHPACK_POLLING=true
      - CI=true
    stdin_open: true
    tty: true
  server:
    build: ./server
    container_name: 5g-sport-server
    ports:
      - "5000:5000"
    depends_on:
      - mediamtx
    devices:
      - /dev/video0:/dev/video0
    privileged: true
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: 5g-sport-mediamtx
    ports:
      - "8554:8554"  # RTSP
      - "8888:8888"  # HLS
      - "8889:8889"  # WebRTC
  nginx:
    image: nginx:latest
    container_name: 5g-sport-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - server
